CREATE TABLE tb_scheduling (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
       title VARCHAR(120) NOT NULL,
       description TEXT,
       start_date TIMESTAMP NOT NULL,
       end_date TIMESTAMP,
       status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
       customer VARCHAR(80) NOT NULL,
       created_in TIMESTAMP NOT NULL DEFAULT NOW(),
       updated_in TIMESTAMP NOT NULL DEFAULT NOW(),
       CONSTRAINT ck_status CHECK (status IN ('SCHEDULED', 'CANCELED', 'COMPLETED')),
       CONSTRAINT ck_interval CHECK (start_date < end_date)
);